spring:
  sql:
    init:
      mode: always
  datasource:
    postgres:
      hikari:
        jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/testdb?currentSchema=public}
        username: ${POSTGRES_USERNAME:postgres}
        password: ${POSTGRES_PASSWORD:admin}
        driver-class-name: org.postgresql.Driver
        auto-commit: false
        minimum-idle: 10
        maximum-pool-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: ${PORT:8080}
flyway:
  baselineOnMigrate: true
  url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/testdb?currentSchema=public}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:admin}
  driver-class-name: org.postgresql.Driver
jwt:
  accessToken:
    signInKey : 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
#    accessTokenExpirationTimeMs : 86400000 # 1 day
    accessTokenExpirationTimeMs : 20000
    refreshTokenExpirationTimeMs : 604800000 # 7 days





